# Generated by Django 3.1.2 on 2020-10-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_person_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Date',
            field=models.DateField(default='2020-10-29'),
        ),
    ]
