# Generated by Django 3.1.2 on 2020-10-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201029_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Date',
            field=models.DateField(max_length=75),
        ),
    ]
